### ISSUE TITLE
Grasp sampling code link is unavailable

### ISSUE THREAD

**Issue by trannguyenle95** [NVlabs/deformable_object_grasping#1]
Hi,
Thanks for your hard work to release this package online. It really motivates the research in the field of deformable object grasping. I would like to report one small thing. When looking at the example.md, I found a link to graspsampling code to generate the grasps candidates. However,  the link is not available for some reasons. Can you please check that? This is the link: [https://gitlab-master.nvidia.com/ceppner/graspsampling-py](https://gitlab-master.nvidia.com/ceppner/graspsampling-py)

**Comment by isabellahuang** [comment]
Hi Tran, we apologize that this repo has not been publicized yet. In the meantime, custom grasps can still be tested as long as the grasp candidates follow the format here: https://github.com/NVlabs/deformable_object_grasping#object_name_graspsh5

**Comment by theshowmaker** [comment]
Hi Isabella, when this antipodal grasp sampler could be publicized? Any clue and plan? Thanks. @isabellahuang
