### ISSUE TITLE
Unable to get raw data

### ISSUE THREAD

**Issue by Malzeee** [NVlabs/deformable_object_grasping#3]
Dear Sir:
When reproducing your project [DefGraspSim](https://github.com/NVlabs/DefGraspSim), we encountered this problem:

1. The files in the DefGraspSim-main/example/rectangle directory are all 0KB or 1KB in size, which may be damaged.

2. We can't clone the repository (https://gitlab-master.nvidia.com/srl/deformable_object_grasping.git), even if you visit the URL directly with a browser, there is no way to access it. Maybe this GitHub project doesn't work anymore.

This results in that we cannot have the raw data of the experiment.

**Comment by isabellahuang** [comment]
Hi, the command is updated now. You may run `git clone git@github.com:NVlabs/DefGraspSim.git`
